### ISSUE TITLE
Getting the message No such file or directory

### ISSUE THREAD

**Issue by Bivin** [workshopper/javascripting#162]
Installed javascripting in ubuntu and after typing javascripting in terminal getting the message "No such file or directory"

**Comment by esalinas00** [comment]
Do you still have this problem?

**Comment by EduardoSouzaDF** [comment]
Same problem

**Comment by aferrar** [comment]
I am having this problem, as well. Any word on this?

**Comment by sethvincent** [comment]
Hi! Could you paste the full error message?

**Comment by aferrar** [comment]
$ cd /usr/local/lib/node_modules/javascripting/
/usr/local/lib/node_modules/javascripting $ ls
bin       javascripting.gif  menu.json     problems        solutions
i18n      lib                node_modules  README.md
index.js  LICENSE.md         package.json  screenshot.png
/usr/local/lib/node_modules/javascripting $ javascripting
**/usr/bin/env: node: No such file or directory**

So, I downloaded node and npm, installed the module, checked the contents in my lib direct and then tried to run javascripting and was met with no such file or directory. Please let me know if there is any more info I can provide and thank you for responding so quickly

**Comment by sethvincent** [comment]
When installing nodejs on ubuntu via `apt-get` it will create a `nodejs` command instead of `node`. It seems like this may be what's going on.

Creating a symlink like this may solve the problem:

```
sudo ln -s /usr/bin/nodejs /usr/bin/node
```

You can also optionally look into installing node via [nvm](https://github.com/creationix/nvm), a version manager that allows you to have multiple versions of node. Not essential for this, but worth checking out.

**Comment by aferrar** [comment]
The symlink worked. You are the man! Thank you and I will definitely check out nvm.=)
