### ISSUE TITLE
Javascripting is not recognized as an internal or external command

### ISSUE THREAD

**Issue by essenauta** [workshopper/javascripting#169]
I am trying to run node.js in the terminal on my school's computer. It runs Windows7 with a 64 bit system. I can run the npm install -g javascripting command fine but I can't draw up the menu with the javascripting command. I repeatedly receive this error: `'javascripting' is not recognized as an internal or external command, operable program or batch file.` I'm running Node.js 6.00.

**Comment by AnshulMalik** [comment]
There are three options that you can try:
1. Open another command prompt and try again.
2. Restart the computer and try again.
3. Add an environment variable called ```NODE_PATH``` and set it to ```%AppData%\npm\node_modules``` and try again.

**Comment by Ullas101** [comment]
This issue is faced because javascripting is a command you execute in windows terminal. To execute a command anywhere in windows it needs to be part of PATH variable. You need to add %AppData%\npm in your PATH variable if you are on windows 7. Correct me If I am wrong- NODE_PATH I believe is the location npm uses when it installs pacakge when gloab parameter is used. More info can be found at [NPM global install “cannot find module”] (https://stackoverflow.com/questions/12594541/npm-global-install-cannot-find-module)
