### ISSUE TITLE
nodeschool-javascripting-variables

### ISSUE THREAD

**Issue by simon01528** [workshopper/javascripting#190]
I am on the second challenge of javascripting titled varialbes and It says to create a new file named variables.js so I went into my atom text editor and created a file named variables.js and then I did the following in the text editor

var example = 'some string';
console.log(example);

then it says to go to the terminal and type javascripting verify variables.js
once I do tha it says o-oh something is not working
I don't understand why it is not working
please help

**Comment by itzsaga** [comment]
In the terminal make sure you are in the same folder that you made the variables.js in.
Example:
If variables.js is `C:\nodeschool\javascripting\variables.js`.
You need to run `javascripting verify variables.js` when you're in `C:\nodeschool\javascripting`.
Let me know if this works or if your problem is something else.

**Comment by itzsaga** [comment]
I haven't heard back from you @simon01528 so I'm closing this. Open up another issue if my suggestion doesn't work.

**Comment by No9** [comment]
Hey we ran into this tonight and the problem is that the current.json in $HOME directory isn't getting updated with the next lesson.
Current workaround is to edit the current.json to say `"STRINGS"` instead of `"VARIABLES"`

**Comment by itzsaga** [comment]
Hey @No9 what OS and terminal did you encounter the issue with?
