### ISSUE TITLE
Call verify from js

### ISSUE THREAD

**Issue by dailez** [workshopper/javascripting#194]
Hi all, 

Is it possible to call javascripting from a js script? I imported it using require, but how to call the verify function with a file as input and getting the terminal output as result?

Many thanks in advance

**Comment by claudiopro** [comment]
Hi @dailez, thanks for asking this question. However, in order to have an answer, you should ask it by [opening an issue](https://github.com/nodeschool/discussions/issues/new) in the [discussions repo](https://github.com/nodeschool/discussions) instead. This repo is only for the development of the javascripting workshop.

**Comment by martinheidegger** [comment]
@dailez Just because i saw this and I have an answer for you: JavaScripting (based on the workshopper-api) actually exposes quite a bit of the API. `run` - the CLI command actually does nothing more than call the logic in here here: https://github.com/workshopper/workshopper-adventure/blob/master/lib/commands/run.js . `.handler(shop,...)` receives nothing more but a reference to `require('javascripting')`. So you would do run like this:

```javascript
const javascripting = require('javascripting')
const filePath = '<file path here>'
const outputStream = javascripting.run([filePath], null, function (err, pass) {
})
outputStream.pipe(somewhere) // somewhere is a placeholder that means: you need to decide what to do with the stream, it will receive markdown code (Likely with Command line colors)
```

**Comment by dailez** [comment]
@martinheidegger Thank you very much for your answer. I got it to work. However, I don't know exactly what JavaScripting is doing now. It runs the file but does it evaluate my file against any problem or solution? I don't think so. Could you give me an example where I define a problem that should be solved with a give file. Thank you very much in advance.

**Comment by dailez** [comment]
@martinheidegger Hi Martin. I found it out myself. So, please forget my question. Thanks again for the advice.
