### ISSUE TITLE
For-each comparison fails with correct output

### ISSUE THREAD

**Issue by bsommardahl** [workshopper/javascripting#199]
I'm running `javascripting` on my Linux Mint VM and the following attempt code is being evaluated as non-match by the cli tool.

```
for(var i=0;i<10;i++){
    console.log(i);
}
```

Here's the tool's output:
```
 Solution ===================

 45

 Your Attempt ===================

 0 1 2 3 4 5 6 7 8 9

 Difference ===================

 0 1 2 3 4 5 6 7 8 9 
```
Here's a screenshot so you can see the coloring: https://cl.ly/1H3t1k1q023E

**Comment by AlexTes** [comment]
@bsommardahl try reading the exercise again: https://github.com/workshopper/javascripting/blob/master/problems/for-loop/problem.md#the-challenge

Is there any part you don't understand? Perhaps you read a translation that looks different?

**Comment by bsommardahl** [comment]
@AlexTes I am sure I understood the exercise. As you can see in my original post, my implementation code should have made the test pass. As you can see in the output, my implementation code DID produce the expected output. But in my screen shot, you can see, from the highlighting, that the output somehow evaluated as different, almost as if there are some invisible characters making the two strings unequal.

**Comment by AlexTes** [comment]
@bsommardahl since you're not getting the expected result and got stuck, perhaps try being a little less confident you know what is going on, and I don't. Either we're misunderstanding each other and you need to elaborate more (which I don't think is the case), or you are not understanding the exercise like I just suggested. Either is okay, but try and fight me a little less on this 😉.

Let's start with the output. The program indicates the solution (expected) is `45`, you're printing (actual) `0 1 2 3 4 5 6 7 8 9` it then shows the difference between the two, highlighting in red all the characters (in this case numbers) that shouldn't be in the output but are.

Perhaps you're confusing the explanation of the for-loop with the challenge you're supposed to solve. The challenge (which I linked before) asks for the following:
>Create a file named for-loop.js.

Can't see if you did, but it looks from the output like you're verifying the correct file.
> In that file define a variable named `total` and make it equal the number 0.

Not in your pasted code.
>Define a second variable named `limit` and make it equal the number 10.

Again, not in your code.

I could go on for all the other steps but I'd rather point back to my previous message. Please read the challenge of the exercise again. I'd be happy to help if anything is still unclear.

**Comment by itzsaga** [comment]
I believe I am to blame. I provided incorrect context (in person) for the problem/solution expected. Although, I think this illustrates #196 and how we need testing that gives better errors.

**Comment by AlexTes** [comment]
@itzsaga alright that's understandable 😄. It would be good if the tests were more helpful by checking for critical components of a correct solution. Perhaps leave a comment here or on #196 explaining how the test is unclear for future reference?

**Comment by itzsaga** [comment]
@AlexTes the test indicates partial correctness, which is misleading in my opinion. This is probably why we never went back and confirmed the problem and just took my word on what we were attempting to solve for 🙄.

**Comment by AndreiAlexandruParaschiv** [comment]
@bsommardahl  I had the same impression as you did : to console.log after each iteration but in fact the task is to console.log(total); after the loop.
The 45 result is the sum of loop numbers (0+1+...+9) 

@AlexTes , @itzsaga - This issue can be closed.

**Comment by itzsaga** [comment]
When we get better testing by solving #196 hopefully the tests will be more verbose in why they fail.
