### ISSUE TITLE
Wrong instructions on for-loop challenge

### ISSUE THREAD

**Issue by JosueDevMark** [workshopper/javascripting#209]
Hi! I was doing the workshopper, but I've find a bug on for-loop challenge.

At the instructions says: `Define a second variable named limit and make it equal the number 10`, but on the verify says that my attemp (result: 10) is wrong, and the solution is 45. 

Could someone clarify what must be solution?

PD:  Attached some screenshot.

Instructions
![instructions](https://user-images.githubusercontent.com/29341826/32086084-182784d0-ba90-11e7-96c5-9d29a986598e.PNG)

Verify
![results](https://user-images.githubusercontent.com/29341826/32086085-1842bac0-ba90-11e7-95ed-c915fc63039e.PNG)

**Comment by itzsaga** [comment]
Hey @UJosue10, can you show is the code you wrote? Thanks.

**Comment by UJosue10** [comment]
Sure @itzsaga, here is:

```javscript
var total = 0, limit = 10;
for (var i = 0; i < limit; i++) {
	total++;
}
console.log(total);
```

**Comment by SomeoneWeird** [comment]
You're only incrementing `total` by `1` each time there, you are supposed to increment it by `limit` each time.

**Comment by itzsaga** [comment]
Actually, you're supposed to increment it by `i` each time. This is directed in the instructions here:
> On each iteration of the loop, add the number `i` to the `total` variable. To do this you can use this statement:
>
> total += i;

**Comment by claudiopro** [comment]
hi @UJosue10, let me summarize what the instructions say:

- The variable `total` has the initial value `0`
- The for loop has a variable `i` starting at `0` by `1` at each iteration
- The loop runs as long as `i < limit`
- On each iteration, add `i` to `total`

The expected solution is as follows:

```
let total = 0;
const limit = 10;
for (let i = 0; i < limit; i += 1) {
  total += i;
}
console.log(total); // 45
```

How can we make them easier to understand? What do you find confusing? Please let us know.

**Comment by SomeoneWeird** [comment]
@itzsaga Sorry, yes, I think I must have typo'd that!

**Comment by Juniper11** [comment]
I know this is a very basic question but how are you able to see the first part of the explanation on the For Loop Question?  

If I were bringing the question up directly from the command prompt I would do:
For Loop more         or 
For Loop head
But because I am reaching the question from Javascripting these options will not work.  

Thanks!

**Comment by itzsaga** [comment]
@UJosue10 does the discussion answer your question?
@Juniper11 I'm not sure I understand what you're asking.

**Comment by UJosue10** [comment]
Thanks a lot to everybody!

> How can we make them easier to understand? What do you find confusing? Please let us know.

Hi @claudiopro, my confusion was because I thought that the `limit` variable should be the result, may can be less confusing if instructions ends with something like `After the for loop, use console.log() to print the total variable to the terminal and verify that total is equal to 45.`

> does the discussion answer your question?

Sure @itzsaga! My question is resolved, thanks.
