### ISSUE TITLE
for-loop issue

### ISSUE THREAD

**Issue by RouGaming** [workshopper/javascripting#220]
Hello! First off all, i have to thank everyone that was involved for the awesome tutorials. I noticed a bug when doing the "for-loop" challenge. It that the result should be 45 which can't be true when the loop runs from 0 to 10 ;)

Only thing i noticed. Still 10/10 cause everyone does mistakes.. Especially me haha

Cheers and greetings form Austria, Rou

**Comment by itzsaga** [comment]
Hello @RouGaming,
I don't think you read the instructions close enough. Let me show you what the solution is looking for:
```js
var total = 0;
var limit = 10;
for (var i = 0; i < limit; i++) {
  total += i;
}
console.log(total);
```
The first time through the loop we add `0` to the `total` variable setting it equal to `0` still. The second time through we add `1` to the `total` variable setting it equal to `1`. The third time through the loop we add `2` to the `total` variable increasing it to `3` because we just added 2 to 1. We continue until we reach the limit of 10 loops. When we look at what `total` is equal to after all of this it is `45`.

Does this make sense?

**Comment by itzsaga** [comment]
Seeing as this just came up again with #224 we should look into the wording of this problem.

**Comment by neenus** [comment]
Hello @itzsaga 
Thank you for your response but I just thought I'd mention I was like many of others who fell for this and ended up with 10 as the answer... I believe I agree with you about the confusing wording.

**Comment by garzo** [comment]
Coming along to mention as well, I too was thrown by the issue and went through several cups of coffee trying to understand how I was getting a different solution than the application. I finally came to the issue tracker, found this and another thread where folks were having the same initial sense of being confounded.

Thanks for the clarification @itzsaga your answer helped me see that the console output in the solution needs to exist outside of the loop; I think many readers of the exercise are getting confused thinking the output of 

`console.log(total);`

is supposed to be *inside* the loop, as it was shown in the example-from reading how it was described in this issue and in #150 

I think if this can be clarified without going over the reader's head, it may ameliorate much confusion for others.

**Comment by itzsaga** [comment]
This also came up in #209 which I referencing here to see why that user had issues with the wording.
