### ISSUE TITLE
EExist problem

### ISSUE THREAD

**Issue by SarahAlAshwal** [workshopper/javascripting#303]
Hi,

After downloading javascripting using : npm install -g javascripting
I tried to run javascripting but I got this error:
EExist: file already exists, mkdir '/home/vagrant/.config/workshopper

I tried to uninstall the app and re-install it but nothing changed.

Please help me.

**Comment by itzsaga** [comment]
@SarahAlAshwal what version of Node are you running?

**Comment by SarahAlAshwal** [comment]
@itzsaga thank you for your reply.
the node version is v8.9.4

**Comment by itzsaga** [comment]
javascripting is only validated against Node.js 10+ since Node.js 8 is no longer maintained. You can see the currently active Node.js versions [here](https://nodejs.org/en/about/releases/). Please upgrade your version and try again. If you still experience the issue feel free to re-open this. I'll make a note to add the supported Node.js version info to the README.

**Comment by SarahAlAshwal** [comment]
@itzsaga thanks a lot
