### ISSUE TITLE
javascripting verify for-loop.js hangs in terminal

### ISSUE THREAD

**Issue by jonopens** [workshopper/javascripting#59]
hello,
I have for-loop.js which contains this:

```
var total = 0
var limit  = 10
for (var i = 0; i < limit; total += i) {
    total =+ i;
};
console.log(total);
```

Whenever I try to run javascripting verify for-loop.js, the terminal just hangs and provides no feedback. What did I do this time :) ?

Thx!

**Comment by sethvincent** [comment]
Take a look at this part: `total += i` inside the parentheses.

Instead of increasing `total` by `i`, it should be increasing `i` by `1` each loop.

So the first part of the for loop would look like this: `for (var i = 0; i < limit; i+=1)`

A shorter way of writing `i+=1` is `i++`.

Sidenote: another place where you can ask these kinds of questions and more people see it is at github.com/nodeschool/discussions/issues

**Comment by jonopens** [comment]
Thanks, I'll try to surface future questions there. For whatever reason, Googling javascripting issues always gives your account.

Would the error I made cause javascripting to not be able to verify my script? My main issue is that the terminal just stops when I put in "javascripting verify for-loop.js"

**Comment by sethvincent** [comment]
Cool. 

Right I forgot to explain why it hangs.

Let's break this down into pieces: `for (var i = 0; i < limit; total += i)`

`var i = 0` sets `i` to `0`.

`i < limit;` checks to make sure `i` is less than `limit`. on the first loop `i` is `0` so it is less than `limit`, which equals `10`.

`total += i` adds `i` to `total`, but both `i` and `total` equal `0`.

This means that on the second loop, `i` still equals `0`. `i` never increases, so the program never breaks out of the loop, because `i` is always less than `limit`.

So it never gets to the `console.log(total);` part of the loop, it just loops forever.
